apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
  namespace: personal-tilen
  labels:
    app: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
        - name: portfolio
          image: localhost:32000/personal/tilen/portfolio:1.0.0
          imagePullPolicy: Always
          resources:
            limits:
              memory: 512Mi
              cpu: '0.25'
          env:
            - name: EMAILJS_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: portfolio-secrets
                  key: emailjs-public-key
            - name: EMAILJS_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: portfolio-secrets
                  key: emailjs-private-key
            - name: EMAILJS_SERVICE_ID
              valueFrom:
                secretKeyRef:
                  name: portfolio-secrets
                  key: emailjs-service-id
            - name: EMAILJS_TEMPLATE_ID
              valueFrom:
                secretKeyRef:
                  name: portfolio-secrets
                  key: emailjs-template-id
